# Read the Docs configuration file
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: backend
      extra_requirements:
        - docs

sphinx:
  configuration: backend/docs/source/conf.py
  builder: html

